### ISSUE TITLE
Getting API  data into React 

### ISSUE THREAD

**Issue by WCNewell** [evernym/ui-challenge#1]
This is my first time calling an api from React. I have since learned in my research that create-react-app does not play nicely with local data. Will you please review the readme to see the overall approach that I am taking for this challenge. I also document what I have tried so far. It seems I may need to build a quick server and deploy that, but I'd like to check in for some advice before going down that path. Meanwhile, I can keep working on getting a placeholder table to render in jsx.

**Comment by tcasey** [comment]
@WCNewell you can add the local data by requiring it in whatever component you'd need it in. `const stuff = require('./data.json')`. (It might be easier to visualize the data you're working with if you `console.log(stuff)` inside of your component's `render` method) And as far as building a quick server to request the data, that's a good approach too 🙂

**Comment by WCNewell** [comment]
Thanks Trevor! I didn't mention that I had tried that before, but, I did get it to work by moving data.json directly into the src folder of the app. This seems like a hack but for the sake of the challenge it will allow me to move forward. Now on to getting required data into a table...
