### ISSUE TITLE
Should I keep working?

### ISSUE THREAD

**Issue by WCNewell** [evernym/ui-challenge#2]
The app is working! I ran a build and deployed to surge. Details are in the readme. Thanks for the extra time as I was working around prior commitments. This "alpha" version does not include any extra responsive design, css, or testing that doesn't already come inherently with react and react-table. I have exceeded the recommended 10 hour time allotment. Should I pursue more responsive design and more detailed testing at this time?

**Comment by tcasey** [comment]
@WCNewell You can submit what you have now but after that, feel free to continue working on it if you like or if you feel like there's something more you wish to show us. To make this process a bit faster, just submit a PR on this repo from your fork.

**Comment by WCNewell** [comment]
Par submitted. I will see if there is more I can do with design and testing. I look forward to feedback on the first submission. Thanks.

**Comment by WCNewell** [comment]
*I mean PR submitted.
